### ISSUE TITLE
tyro.conf.arg aliases not working in Pydantic>=2

### ISSUE THREAD

**Issue by mhuerta-endava** [brentyi/tyro#110] opened 2023-12-21 13:44 UTC
```python
# tyrotest.py
from typing import Annotated

import tyro
from pydantic import BaseModel
from tyro.conf import arg

class AliasCfg(BaseModel):
    alias: Annotated[str, arg(aliases=["-a"])]

cfg = tyro.cli(AliasCfg)
print(f"Alias: {cfg.alias}")
```

With Pydantic < 2:
```console
$ python tyrotest.py
usage: tyrotest.py [-h] --alias STR

╭─ arguments ─────────────────────────────────────────────╮
│ -h, --help              show this help message and exit │
│ --alias STR, -a STR     (required)                      │
╰─────────────────────────────────────────────────────────╯
```

With Pydantic >=2:
```console
$ python tyrotest.py
usage: tyrotest.py [-h] --alias STR

╭─ arguments ────────────────────────────────────────╮
│ -h, --help         show this help message and exit │
│ --alias STR        (required)                      │
╰────────────────────────────────────────────────────╯
```
and of course the alias is not recognized on invocation.

With functions and dataclasses the alias works perfectly.

**Comment by brentyi** [comment] 2023-12-22 00:08
Hi Marcelo, thanks for filing this + the detailed reproduction instruction!

This is actually fixed in the branch for #106, which I'll try to merge + release today. I can add your example to the tests to prevent regressions.

**Closed** 2023-12-22 05:37 UTC

**Comment by brentyi** [comment] 2023-12-22 05:39
Should be fixed in `0.6.1`!

**Comment by mhuerta-endava** [comment] 2023-12-22 14:05
> Should be fixed in `0.6.1`!

Can confirm. Thanks!

**Comment by scottstanie** [comment] 2024-02-08 22:01
Is there some reason we shouldn't be able to alter the annotations after the initial class definition?

```
# tyrotest.py
from typing import Annotated

import tyro
from pydantic import BaseModel
from tyro.conf import arg


class AliasCfg(BaseModel):
    alias: str


AliasCfg.__annotations__["alias"] = Annotated[str, arg(aliases=["-a"])]
cfg = tyro.cli(AliasCfg)
print(f"Alias: {cfg.alias}")
```

This does not print the `-a` (but replacing pydantic with `@dataclass` does show this alias)

**Comment by brentyi** [comment] 2024-02-08 23:31
Mechanically, the reason is that we use pydantic's [`model_fields`](https://docs.pydantic.dev/latest/api/base_model/#pydantic.BaseModel.model_fields) dictionary to extract types + metadata. This dictionary will be generated before your annotations update here (I believe during `BaseModel`'s `__init_subclass__`).

I have mixed feelings about this pattern , but here's an alternative that should work in pydantic v2:
```python
from typing import Annotated

import tyro
from pydantic import BaseModel
from tyro.conf import arg


class AliasCfg(BaseModel):
    alias: str


AliasCfg.model_fields["alias"].metadata.append(arg(aliases=["-a"]))

cfg = tyro.cli(AliasCfg)
print(f"Alias: {cfg.alias}")
```

**Comment by scottstanie** [comment] 2024-02-08 23:49
thank you! I'll try that out.
I agree that it feels a little fragile to the inner workings of Pydantic... but I'm not sure of a better way to do this- the configuration class is defined elsewhere, and doesn't know anything about `tyro.conf.arg`. I'm open to ideas about that if you have any.

**Comment by brentyi** [comment] 2024-02-09 00:18
Ok!

I guess another option is to subclass and override just the fields you want to add aliases for:
```python
# tyrotest.py
from typing import Annotated

import tyro
from pydantic import BaseModel
from tyro.conf import arg


class ExternalCfg(BaseModel):
    alias: str


class AliasedCfg(ExternalCfg):
    alias: Annotated[str, arg(aliases=["-a"])]


cfg = tyro.cli(AliasedCfg)
print(f"Alias: {cfg.alias}")
```

Although maybe this doesn't work if it's deeply nested.
